name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build artifacts
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          body: |
            ## Кратко
            - Обновление DiaGen CLI
            - Артефакты сборки приложены в секции Assets
            - Подробности по изменениям добавлены в авто-сгенерированных Release Notes

            ## Установка
            - Установите нужный артефакт из секции Assets через `pip`
          generate_release_notes: true
